name: API with Pactum CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@v3.9.1
      with:
        node-version: 'node'

    - name: Install dependencies
      run: npm install

    - name: Run tests & Generate reports
      run: npm run test:report

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: mochawesome-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report
